### Artificial Neural Network - Part 1

In [21]:
# Notebook settings 
import warnings
warnings.filterwarnings("ignore")
import matplotlib
%matplotlib inline
matplotlib.rcParams['font.size'] = 16
matplotlib.rcParams['figure.figsize'] = (9,9)
'''
# Data Preprocessing 
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 
dataset = np.array([[11,11,0], [13,11,0], [8,10,0], [9,9,0], [7,7,0], [7,5,0], [15,3,0], [7,11,1], [15,9,1], [15,7,1], [15,5,1], [14,4,1], [9,3,1], [11,3,1]])
plt.scatter(dataset[:,0], dataset[:,1], c=dataset[:,2]) 
plt.show()

'''

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values = np.array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([np.argmax(onehot_encoded[0, :])])
print(inverted)




['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[0 0 2 0 1 1 2 0 2 1]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
['cold']


In [4]:
name= "Python"
print(name[-1])
print(name[2:])

n
thon


In [ ]:
## Create new line and append to  a dataframe with Pandas 
#print(data.tail())
#next_date = datetime.datetime.utcfromtimestamp(next_day).strftime('%Y-%m-%d')
#new_data = pd.DataFrame(np.nan, index=[next_date], columns=data.columns)
#data = data.append(new_data)
#data.loc[next_date] = [np.nan for _ in range( len(data.columns)-1 )] + [1]