# Data generation 

## Import libs

In [1]:
import os
import random
import string
import numpy as np
import matplotlib.pyplot as plt
import cv2
from PIL import Image


%matplotlib inline
plt.style.use('fivethirtyeight')
plt.rcParams['figure.facecolor'] = 'w'
plt.rcParams['figure.figsize'] = [12, 8]
plt.rcParams['font.size'] = 14

In [2]:
# Load dataset
PATH = 'dataset/train/'

In [6]:
# Redefine predicted mask fo visualization 
def generate_predict(path):
    for img_id in os.listdir(path + "predict_masks/"):
        mask_in = cv2.imread(path + 'predict_masks/' + img_id)
        mask_in_gray = cv2.cvtColor(mask_in, cv2.COLOR_BGR2GRAY)
        print(mask_in_gray)
        print(np.unique(mask_in))
        
generate_predict(PATH)

[[155 155 155 ... 216 216 216]
 [155 155 155 ... 216 216 216]
 [155 155 155 ... 216 216 216]
 ...
 [155 155 155 ... 155 155 155]
 [155 155 155 ... 155 155 155]
 [155 155 155 ... 155 155 155]]
[ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109
 110 111 112 113 114 115 116 117 118 119 120 122 123 124 125 126 127 128
 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146
 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164
 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182
 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200
 201 202 203 204 205 206 207 215 216 217 218 219 220 221 222 223 224 225
 226 

In [165]:
# Random image name generator
def get_name(size=30, chars=string.ascii_letters + string.digits):
    return ''.join(random.choice(chars) for x in range(size))

In [174]:
# Normalize mask channels
# Generate annotation images [0: Background, 1: occluded_road, 2: road]
def generate_annot(path):
    for img_id in os.listdir(path + "masks/"):
        img_fname = img_id.split('.')[0]
        # Get mask
        mask_in = cv2.imread(path + 'masks/' + img_id)
        G_mask = mask_in[:,:,1] == 128
        mask_in[G_mask] = 1
        R_mask = mask_in[:,:,2] == 128
        mask_in[R_mask] = 2
        # Save new normalized mask 
        cv2.imwrite(path + 'masks_final/' + img_fname + '.png', mask_in)
#generate_annot(PATH)

In [185]:
# Regenerate mask for visualization
def regenerate_annot(path):
    for img_id in os.listdir(path + "masks_out/"):
        img_fname = img_id.split('.')[0]
        #print(img_id)
        # Get mask
        mask_in = cv2.imread(path + 'masks_out/' + img_id, 1)
        #print(mask_in.shape)
        # Split channel 
        B, G, R = cv2.split(mask_in)
        G_mask = G == 1
        G[G_mask] = 128
        R_mask = R == 2
        R[R_mask] = 128
        mask_out = cv2.merge((B, G, R))
        # Save new normalized mask 
        cv2.imwrite(path + 'masks_origin/' + img_fname + '.png', mask_out)
#regenerate_annot(PATH)

In [176]:
# image slicing - run once 
def generate_slice(path):
    for img_id in os.listdir(path + "images/"):
        img_fname = img_id.split('.')[0]
        # randomn name
        out_name = ''.join([random.choice(string.ascii_letters + string.digits) for n in range(40)])
        # Convert jpg to png
        img_in = Image.open(path + 'images/' + img_fname + '.jpg')
        img_in.save(path + 'images/' + img_fname + '.png')
        
        # Get image and path 
        img_in = cv2.imread(path + 'images/' + img_fname + '.png')
        mask_in = cv2.imread(path + 'masks_final/' + img_fname + '.png')
        
        h = img_in.shape[0] // 2
        w = img_in.shape[1] // 2
        # Generate sliced image/mask and save
        img_out_1 = img_in[:h, :w]
        img_out_2 = img_in[:h, w:]
        img_out_3 = img_in[h:, :w]
        img_out_4 = img_in[h:, w:]
        # Generate sliced mask and save 
        mask_out_1 = mask_in[:h, :w]
        mask_out_2 = mask_in[:h, w:]
        mask_out_3 = mask_in[h:, :w]
        mask_out_4 = mask_in[h:, w:]
        
        name_1 = get_name()
        cv2.imwrite(path + 'images_out/' + name_1 + '.png', img_out_1)
        cv2.imwrite(path + 'masks_out/' + name_1 + '.png', mask_out_1)
        name_2 = get_name()
        cv2.imwrite(path + 'images_out/' + name_2 + '.png', img_out_2)
        cv2.imwrite(path + 'masks_out/' + name_2 + '.png', mask_out_2)
        name_3 = get_name()
        cv2.imwrite(path + 'images_out/' + name_3 + '.png', img_out_3)
        cv2.imwrite(path + 'masks_out/' + name_3 + '.png', mask_out_3)
        name_4 = get_name()
        cv2.imwrite(path + 'images_out/' + name_4 + '.png', img_out_4)
        cv2.imwrite(path + 'masks_out/' + name_4 + '.png', mask_out_4)
        
#generate_slice(PATH)

In [ ]:
def generate_slice(path):
    for img_id in os.listdir(path + "images/"):

# Code test

In [188]:
#PATH2 = 'dataset1/annotations_prepped_test/'
img2_in = cv2.imread(PATH + 'predicts/UxbHQBhVCGz1I22q0z9gwhwsdmyN8M.png')
#img2_in = cv2.cvtColor(img2_in, cv2.COLOR_BGR2RGB)
B, G, R = cv2.split(img2_in)

In [139]:
# Data augmentation test 
import numpy as np
import imgaug as ia
import imgaug.augmenters as iaa
ia.seed(1)
# Example batch of images.
# The array has shape (32, 64, 64, 3) and dtype uint8.
images = np.array(
    [ia.quokka(size=(64, 64)) for _ in range(32)],
    dtype=np.uint8
)
#plt.imshow(images[30,:,:,:])